### ISSUE TITLE
About constraints on debiasing contexts

### ISSUE THREAD

**Issue by Yun-Fu** [ntkien1904/DegFairGNN#2]
Hello, I am reading your paper and it is a wonderful work. But I am so confused about the constraints on debiasing contexts in paper. Could you please help me? 
First, the debiasing context of low-degree nodes is to complement the neighborhood information of low-degree nodes. Why should it be close to 0? Isn't it the bigger the better? Because the larger it is, the more neighborhood information is complemented, and the more it can help the current node to debias?
Second, for high-degree nodes, does the debiasing context want to purify the field and delete some unnecessary information? But there is less unnecessary information, so it should be close to 0? Is this correct to understand?
I'm looking forward to your reply, thank you very much! @ntkien1904

**Comment by ntkien1904** [comment]
Hi Yun-Fu,

Thanks for your interest in our work. To clarify your concern, there are two debiasing context modules: D(v, \theta_0) to complement and D(v, \theta_1) to distill. Thus, D(v, \theta_0) should be close to 0 on high-degree nodes (not all nodes) since we aim to distill the high-degree nodes (yes like you interpret: purify unnecessary information). Similarly, D(v, \theta_1) should be close to 0 on low-degree nodes, not all nodes. You can check the notation in the paper.

I hope my answer addresses your concern. Let me know if you have other issues.

**Comment by Yun-Fu** [comment]
Thank you very much for your reply, but I still don't understand why the debiasing function of low-degree nodes D(v, \theta_1) 
 should be close to 0. Isn't it used to supplement low-degree nodes? So shouldn't it be as large as possible? Because the larger it is, the more information it can provide.

**Comment by Yun-Fu** [comment]
Thanks for your reply!I understand it!
